"use strict";

module.exports = {
  url: "https://tomfaulkner.org",
  title: "Developer Diary",
  tagline: "Insert something funny yet relevant here",
  copyright: "© 2019 Tom Faulkner, All rights reserved",
  author: {
    name: "Tom Faulkner",
    bio:
      "I write code; I solve problems; I solve problems with code; I sip good bourbon and craft beer.",
    contacts: {
      linkedin: "https://www.linkedin.com/in/tomfaulkner1/",
      github: "https://github.com/tomfaulkner",
      stackoverflow: "",
      freecodecamp: "",
      twitter: "https://twitter.com/tomf80",
    },
  },
  labels: [
    // https://react-icons.netlify.com
    {
      tag: "react",
      tech: "React",
      name: "DiReact",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "nodejs",
      tech: "Node.js",
      name: "DiNodejsSmall",
      size: 20,
      color: "lightgreen",
    },
    {
      tag: "git",
      tech: "Git",
      name: "DiGitMerge",
      size: 20,
      color: "white",
    },
    {
      tag: "javascript",
      tech: "JavaScript",
      name: "DiJsBadge",
      size: 20,
      color: "yellow",
    },
    {
      tag: "css",
      tech: "CSS",
      name: "DiCss3Full",
      size: 20,
      color: "teal",
    },
    {
      tag: "python",
      tech: "Python",
      name: "DiPython",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "ruby",
      tech: "Ruby",
      name: "DiRuby",
      size: 20,
      color: "crimson",
    },
    {
      tag: "java",
      tech: "Java",
      name: "FaJava",
      size: 20,
      color: "wheat",
    },
    {
      tag: "angular",
      tech: "Angular",
      name: "DiAngularSimple",
      size: 20,
      color: "red",
    },
    {
      tag: "html",
      tech: "HTML",
      name: "FaHtml5",
      size: 20,
      color: "darkorange",
    },
    {
      tag: "php",
      tech: "php",
      name: "DiPhp",
      size: 20,
      color: "violet",
    },
    {
      tag: "mongodb",
      tech: "MongoDB",
      name: "DiMongodb",
      size: 20,
      color: "green",
    },
    {
      tag: "vscode",
      tech: "VS Code",
      name: "DiVisualstudio",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "meta",
      tech: "Meta",
      name: "IoIosMore",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "education",
      tech: "Education",
      name: "IoIosBook",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "automation",
      tech: "Automation",
      name: "FiSettings",
      size: 20,
      color: "grey",
    },
  ],
};
